obj-m += appleCP_driver.o



all:
	make -C /home/krishna.vasu/renesas/build/tmp/work/lager-poky-linux-gnueabi/linux-yocto/3.4+gitd12dc4c7e7368c29f6710a4bbcc547e2699e9bac-r15/git  CROSS_COMPILE=arm-linux-gnueabihf- ARCH=arm  M=$(PWD) modules 

clean:
	make -C /home/krishna.vasu/renesas/build/tmp/work/lager-poky-linux-gnueabi/linux-yocto/3.4+gitd12dc4c7e7368c29f6710a4bbcc547e2699e9bac-r15/git  CROSS_COMPILE=arm-linux-gnueabihf- ARCH=arm M=$(PWD) clean

